[package]
name = "wasm-in-wasm-imports"
version = "0.0.0"
authors = ["The wasm-bindgen Developers"]
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = { path = "../../" }
js-sys = { path = "../../crates/js-sys" }
wasm-bindgen-futures = { path = "../../crates/futures" }
