[package]
name = "wasm-bindgen-webidl"
version = "0.0.0"
authors = ["The wasm-bindgen Developers"]
edition = "2021"
publish = false

[dependencies]
env_logger = "0.11.5"
anyhow = "1.0"
heck = "0.5"
log = "0.4.1"
proc-macro2 = "1.0"
quote = '1.0'
syn = { version = '2.0', features = ['extra-traits', 'full'] }
wasm-bindgen-backend = { path = "../backend" }
weedle = { git = "https://github.com/rustwasm/weedle.git" }
once_cell = "1.12"
sourcefile = "0.2"
structopt = "0.3.9"
lazy_static = "1.4.0"
