[package]
name = "console_log"
version = "0.0.0"
authors = ["The wasm-bindgen Developers"]
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = { path = "../../" }
web-sys = { path = "../../crates/web-sys", features = ['console'] }
