[package]
name = "performance"
version = "0.0.0"
authors = ["The wasm-bindgen Developers"]
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = { path = "../../" }
humantime = "2"

[dependencies.web-sys]
path = "../../crates/web-sys"
features = ['Window', 'Performance', 'PerformanceTiming']
